github:
  features:
    wiki: true
  description: "Apache EventMesh (Incubating) Website"
  homepage: https://eventmesh.apache.org

staging:
  profile: ~
  whoami: asf-site

publish:
  whoami: asf-site

notifications:
  commits: commits@eventmesh.apache.org
  issues: commits@eventmesh.apache.org
  pullrequests_status: commits@eventmesh.apache.org
  pullrequests_comment: commits@eventmesh.apache.org
  issues_status: dev@eventmesh.apache.org
  issues_comment: commits@eventmesh.apache.org
  jira_options: link label worklog
